#!D:\.Faculdade\Visao_Computacional\2025_2\mesh3d-generator-py3.11\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
